[tools]
"go:crdx.org/cmd/chronic" = "latest"
"go:crdx.org/cmd/uchar" = "latest"
"go:crdx.org/cmd/unbuffer" = "latest"
"go:crdx.org/cmd/ver" = "latest"
golangci-lint = "latest"

[env]
_.path = ["bin"]
